### ISSUE TITLE
Trying to get the example to work.

### ISSUE THREAD

**Issue by marshallswain** [frandiox/vitedge#6] opened 2021-02-22 01:42 UTC
Hi, @frandiox, it's me again!

I'm doing my best to figure this out, and please pardon my complete ignorance in this area.  I'm very grateful for your work and plan on joining the cause as soon as I can come to a full comprehension.  I'm really excited to show [feathers-vuex](https://vuex.feathersjs.com/) users how to use it for a stellar setup with FeathersJS.  Since you said you are open to suggestions and support with the experience of getting up and running, I have a couple of thoughts.  One would be to move the vitedge vue example into a its own github repo so it can be one-click cloned to create a new project.  That would make it just one click to start a new, working project.  For clarity, here's a screenshot of the Vitesse repo that shows the "Use this template" button:

![Screen Shot 2021-02-21 at 6 35 55 PM](https://user-images.githubusercontent.com/128857/108646613-bc0d9580-7473-11eb-8914-9190bc2c0003.jpg)

Having a template repo would make it easier to get up and running after breaking changes.

I attempted to create this repo myself by cloning the vitedge project and moving the vue example to the top level.  Please check my repo, here: https://github.com/marshallswain/vitedge.

My goal is to make it possible to clone and just be able to run `npm run dev` and have it just work.  In this case, I did update the packages to the latest patch release, which maybe is causing the problem that I'm running into.  This is the error message I'm getting:

![Screen Shot 2021-02-21 at 6 40 39 PM](https://user-images.githubusercontent.com/128857/108646821-58379c80-7474-11eb-9340-970934639076.jpg)

![Screen Shot 2021-02-21 at 6 30 02 PM](https://user-images.githubusercontent.com/128857/108646817-540b7f00-7474-11eb-8098-f67f23e7160f.jpg)

It's not clear to me why this is occurring.  Any support in getting the example to run would be especially appreciated.  Thank you!

**Comment by frandiox** [comment] 2021-02-22 04:19
@marshallswain There's nothing to pardon! And thanks a lot for your interest 🙏 This project is still under development so it is completely normal to have issues 😅 

The examples in this repo are meant mostly for my own testing. I had the intention of creating a `vitessedge` template, and in fact I have a local version of it but very outdated. I'll try to make some time to update and publish it as soon as possible.

For your example, since you want Feather JS but Vitedge already provides a way to create APIs, perhaps it would be better to use [vite-ssr](https://github.com/frandiox/vite-ssr) instead? That one is the core of Vitedge, minus the API part and the CF Worker workarounds.

In any case, I'll check your repo later today when I have some more time 👍

**Comment by marshallswain** [comment] 2021-02-22 06:38
Thanks for the recommendation.  I actually just got it up and running.  I’m actually still very much interested in using Vitedge to publish to Cloudflare.  I’ll be demonstrating how to use Vitedge/CF Workers as a caching proxy to FeathersJS, while still receiving the realtime updates over WebSocket.  Eventually, I see this all migrating to CF Durable Objects instead of proxying another server (once it’s out of beta).

I really like how easy you’ve made the handoff from SSR server to client by just adding it to the `initialState` object.  That seems perfectly flexible.

Thanks for checking out the repo.

**Comment by frandiox** [comment] 2021-02-22 11:28
@marshallswain Ah I see, I just downloaded your repo and it worked with `yarn && yarn dev` so I guess you fixed the problem.

>I’ll be demonstrating how to use Vitedge/CF Workers as a caching proxy to FeathersJS, while still receiving the realtime updates over WebSocket

That's interesting. So you are going to deploy your API somewhere else? I guess I don't know much about FeatherJS 😅 

One limitation of CF workers is that they cannot make requests to themselves. But if your API lives in a different platform then it shouldn't be a problem.
I guess you would be making requests to your API from Vitedge's page props handlers? Or directly from the Vue components using `serverPrefetch`?

**Comment by marshallswain** [comment] 2021-02-22 16:00
@frandiox I'll try with yarn, today.  I was using `npm` for my test.  I also noticed a similar problem with `vue-ssr`.  When I tried using pnpm, I ran into errors.  When I used `yarn` it worked perfectly.

> That's interesting. So you are going to deploy your API somewhere else? I guess I don't know much about FeatherJS 😅

Yes, I'll deploy the API server to Azure App Platform.  FeathersJS is very unique in how it thinks about making APIs.  It has a   "Service"  class that works as a common interface to communicate over rest or as a GraphQL gateway much like Express.  Each "service" is basically a gateway to a database table or another API.  So I'll be creating a local API file in Vitedge that proxies to the API server on Azure.  So publishing to the edge is mostly about cache.  FeathersJS is also the only framework of which I'm aware that puts WebSocket communication as a first-class citizen (as opposed to being bolted on top of plain HTTP requests).  

So I'm going to show how to keep the advantages of the real-time socket connections directly from the server while using the workers on the edge servers for the cache.  feathers-vuex is a utility I made for Vue that enables live lists and queries with a fall-through cache on a local database, which was based on my experience in the early years of Meteor.  I'm super stoked about the performance between the Edge Side Rendering and the Edge-based APIs.

> One limitation of CF workers is that they cannot make requests to themselves.

Ooh.  This is something I did not know.  That's an interesting limitation that may result in always requiring the separate API server.  It will be interesting to see how things evolve once Durable Objects are complete.

Thanks again!  I'll try again with Yarn and let you know how it goes.

**Comment by marshallswain** [comment] 2021-02-23 01:55
I only had my M1 MacBook Pro, today, so I was unable to test this.  I guess that brings up the point that this doesn't work on Apple Silicon machines.  I don't think it's something within your control, though.  I can open a separate issue, if you'd like.  Anyway, I will test this on my Intel machine, tomorrow then get it closed or discuss further.  Thanks!

**Comment by frandiox** [comment] 2021-02-23 15:54
>I'll try with yarn, today. I was using npm for my test. I also noticed a similar problem with vue-ssr. When I tried using pnpm, I ran into errors. When I used yarn it worked perfectly.

Hmmm... weird, all of them seem to work for me. In fact, I just released this template for `vite-ssr` using `pnpm` (my first time) and seems to be working: https://vitesse-ssr.vercel.app/

>So I'm going to show how to keep the advantages of the real-time socket connections directly from the server while using the workers on the edge servers for the cache. feathers-vuex is a utility I made for Vue that enables live lists and queries with a fall-through cache on a local database, which was based on my experience in the early years of Meteor. I'm super stoked about the performance between the Edge Side Rendering and the Edge-based APIs.

Sounds great. It would be interesting to have an example of all of that since I might need it myself (especially websockets) at some point for a side project :)

> this doesn't work on Apple Silicon machines

I think the only binary that this uses is ESBuild (Vite uses it internally) and it recently released a M1 binary but might not be publicly available yet. You might need Rosetta I guess 🤔  Other than that I've no idea what else can be breaking.


If the thing keeps failing, you can try to run it locally without SSR (remove the --ssr flag from the CLI) so at least you can get started with an SPA. Maybe test also the build command and see if that works for you. The SSR local dev is the hairiest feature, I've found some inexplicable crashes randomly that I think come from Vite core itself but it's quite hard to make a minimal reproduction...

**Comment by frandiox** [comment] 2021-02-28 14:34
@marshallswain I'm making a template using Vitesse and I just found a problem with `pnpm` related to `ts-node`. It works well with `yarn` and `npm`. What was the error you found related to `ts-node` (`Expected string to be returned for the "format" from the "loader getFormat" function but got type object`)?

**Comment by frandiox** [comment] 2021-03-01 18:04
@marshallswain I just published the templated I mentioned: https://github.com/frandiox/vitessedge-template

**Comment by frandiox** [comment] 2021-04-16 14:04
@marshallswain I'm closing this for now, feel free to comment or reopen if you get some free time again to test FeatherJS in CF.

**Closed by frandiox** 2021-04-16 14:04 UTC
